PROCESS_NAME_SPLIT_CHAR = '>'
PROCESS_ENDLESS_FULL_NETWORK_SCAN_NAME = 'endless_full_network_scan'
PROCESS_ENDLESS_NMAP_SCAN_NAME = 'endless_nmap_scan'
PROCESS_ENDLESS_OSQUERY_SCAN_NAME = 'endless_osquery_scan'
PROCESS_ENDLESS_ZIGBEE2MQTT_STATE_NAME = 'endless_zigbee2mqtt_state'
PROCESS_ENDLESS_MOSQUITTO_SCAN_NAME = 'endless_mosquitto_scan'
SERVICE_LIST = [PROCESS_ENDLESS_FULL_NETWORK_SCAN_NAME,
                PROCESS_ENDLESS_NMAP_SCAN_NAME,
                PROCESS_ENDLESS_OSQUERY_SCAN_NAME,
                PROCESS_ENDLESS_ZIGBEE2MQTT_STATE_NAME,
                PROCESS_ENDLESS_MOSQUITTO_SCAN_NAME]
